#!/usr/bin/env python

from tgastars.data import update_completed

if __name__=='__main__':

    parser = argparse.ArgumentParser(description='Figure out what is ready to fit and what has been fit.')

    parser.add_argument('--test', action='store_true')

    args = parser.parse_args()


    update_completed(test=args.test)