#!/usr/bin/env python
import sys, os
import argparse

from tgastars.write import write_ini
from multiprocessing import Pool

if __name__=='__main__':

    parser = argparse.ArgumentParser(description='Write star.ini files for given indices of TGAS table')

    parser.add_argument('indices', nargs='*', type=int)
    parser.add_argument('-o','--overwrite', action='store_true')
    parser.add_argument('-v','--verbose', action='store_true')
    parser.add_argument('-p','--processes', type=int, default=1)

    args = parser.parse_args()

    pool = Pool(processes=args.processes)
    pool.map(write_ini, args.indices)

