#!/usr/bin/env python
import sys, os
import argparse

from tgastars.write import write_ini

if __name__=='__main__':

    parser = argparse.ArgumentParser(description='Write star.ini files for given indices of TGAS table')

    parser.add_argument('indices', nargs='*', type=int)
    parser.add_argument('-o','--overwrite', action='store_true')
    parser.add_argument('-v','--verbose', action='store_true')

    args = parser.parse_args()

    n = len(args.indices)
    for i in args.indices:
        try:
            write_ini(i)
        except:
            print('Error with index {}'.format(i))
